- name: Find existing webservices-rest omod
  find:
    paths: /opt/openmrs/modules
    patterns: webservices-rest*.omod
  register: result

- name: Delete webservices-rest omod
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ result.files }}"

- name: Get webservices-rest from GitHub and place it in /opt/openmrs/modules
  get_url:
      url: "{{ webservices }}"
      dest: /opt/openmrs/modules/webservices-rest.omod
      mode: 0644
- name: Change ownership of webservices-rest file
  action: file state=file path=/opt/openmrs/modules/webservices-rest.omod owner=bahmni group=bahmni
