- name: Find existing patient identifier generator omod
  find:
    paths: /opt/openmrs/modules
    patterns: patientidentifiergenerator*.omod
  register: result

- name: Delete patient identifier generator omod
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ result.files }}"

- name: Get patient identifier generator from GitHub and place it in /opt/openmrs/modules
  get_url:
      url: "{{ patientidentifiergenerator }}"
      dest: /opt/openmrs/modules/patientidentifiergenerator.omod
      mode: 0644
- name: Change ownership of patient identifier generator file
  action: file state=file path=/opt/openmrs/modules/patientidentifiergenerator.omod owner=bahmni group=bahmni
