- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: bahmni-mysql-cache-properties, tags: mysql_cache }
    - { role: bahmni-92-mysql-performance, tags: mysql_performance }
    - { role: appointments, tags: appointments }
    - { role: bahmni-core, tags: bahmni-core }
    - { role: bahmni-ie-apps, tags: bahmni-ie-apps }
    - { role: bahmni-msf-module, tags: bahmni-msf-module }
    - { role: bahmni-apps, tags: bahmni-apps }
    - { role: implementer-interface, tags: implementer-interface }
    - { role: bahmni-amman-exports, tags: bahmni-amman-exports }
    - { role: print-forms, tags: print-forms }
    - { role: appointment-frontend, tags: appointment-frontend }
