- hosts: localhost
  become: yes
  roles:
    - { role: bahmni-core, tags: bahmni_core }
    - { role: bahmni-apps, tags: bahmni_apps }
    - { role: implementer-interface, tags: implementer_interface  }
    - { role: bahmni-ie-apps, tags: bahmni_ie_apps }
    - { role: appointments, tags: appointments }
    - { role: appointment-frontend, tags: appointment_frontend }
    - { role: patient-identifier-generator, tags: patient_identifier_generator }
    - { role: visit-close-module, tags: visit_close_module }
    - { role: openconceptlab, tags: openconceptlab }
    - { role: initializer, tags: initializer }
